name: PVS-Studio build analysis
on:
  push:
jobs:
  build-analyze:
    runs-on: pvs
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Analyze
        run: |
          chmod 777 ./script.sh
          ./script.sh
      - name: Publish report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./results.sarif
