name: PVS-Studio build analysis
on: workflow_dispatch
jobs:
  build-analyze:
    runs-on: pvs
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Analyze
        run: ./script.sh
      - name: Publish report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
          category: PVS-Studio
